# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.qrneo-network.com:
  peer0.taguig.qrneo-network.com:
  peer1.taguig.qrneo-network.com:
  peer0.magsaysay.qrneo-network.com:
  peer1.magsaysay.qrneo-network.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-taguig
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.taguig.qrneo-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.taguig.qrneo-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerTaguig
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-magsaysay
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.magsaysay.qrneo-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.magsaysay.qrneo-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMagsaysay
    networks:
      - byfn

  orderer.qrneo-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.qrneo-network.com
    container_name: orderer.qrneo-network.com
    networks:
      - byfn

  peer0.taguig.qrneo-network.com:
    container_name: peer0.taguig.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.taguig.qrneo-network.com
    networks:
      - byfn

  peer1.taguig.qrneo-network.com:
    container_name: peer1.taguig.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.taguig.qrneo-network.com
    networks:
      - byfn

  peer0.magsaysay.qrneo-network.com:
    container_name: peer0.magsaysay.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.magsaysay.qrneo-network.com
    networks:
      - byfn

  peer1.magsaysay.qrneo-network.com:
    container_name: peer1.magsaysay.qrneo-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.magsaysay.qrneo-network.com
    networks:
      - byfn
